### PR TITLE
Migrate to Fluentd v0.14 API

### PR DESCRIPTION
**Pull request by okkez**

### CODE REVIEW

**Comment by kentaro** [comment]
Thank you! If it' merged, we should update the minor version, shouldn't we?

**Comment by okkez** [comment]
Thank you for quick response!
We should update the major or minor version.

See http://docs.fluentd.org/v0.14/articles/plugin-update-from-v12#5-release-new-version

**Comment by kentaro** [comment]
Got it!

**Comment by kentaro** [comment]
Released as v0.1.1

**Comment by repeatedly** [comment]
Updating README is also needed to refer support fluentd versions.
Some users will hit the problem "I installed extract_query_params with td-agent but it doesn't work. why?"

**Comment by kentaro** [comment]
Does the PR make sense? https://github.com/kentaro/fluent-plugin-extract_query_params/pull/26

**Pull request merged**
