### PR TITLE
Update .travis.yml

### PR DESCRIPTION
**Pull request by okkez**
See https://docs.travis-ci.com/user/workers/container-based-infrastructure/

### CODE REVIEW

**Comment by okkez** [comment]
@kentaro ping?

**Comment by okkez** [comment]
@kentaro Do you have any concern?

**Comment by okkez** [comment]
@kentaro ping?

**Comment by kentaro** [comment]
Pong! Will merge it! Sorry for slow response!

**Comment by okkez** [comment]
Thanks!

**Pull request merged**
